language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

before_script:
  - composer install --dev --prefer-source

after_script:
  - php vendor/bin/coveralls -v 

before_install:
  - composer self-update
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.32.tar.gz
  - tar -zxvf Image-ExifTool-9.32.tar.gz
  - cd Image-ExifTool-9.32 && perl Makefile.PL && make test && sudo make install
  - cd .. && rm -rf Image-ExifTool-9.32
