language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  - DEPENDENCIES=no
  - DEPENDENCIES=beta
  - DEPENDENCIES=low

matrix:
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
    - env: DEPENDENCIES=beta
    - env: DEPENDENCIES=low

script:
  - mkdir -p build/logs
  - composer validate-files
  - composer check-code-style
  - composer run-tests

before_script:
  - if [ "$DEPENDENCIES" = "low" ]; then composer -vvv --prefer-lowest --prefer-stable update; else composer update; fi;

after_script:
  - php vendor/bin/php-coveralls -v

before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - composer self-update
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-11.77.tar.gz
  - tar -zxvf Image-ExifTool-11.77.tar.gz
  - cd Image-ExifTool-11.77 && perl Makefile.PL && make test && sudo make install
  - cd .. && rm -rf Image-ExifTool-11.77
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  # Prevent Travis throwing an out of memory error
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Test if we have a token for github in case the project hits the 60 rph limit
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
